# Generated by Django 4.0.3 on 2022-04-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
    ]
