# Generated by Django 4.0.3 on 2022-04-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantManager', '0002_alter_restaurant_attributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='publish_data',
            new_name='publish_date',
        ),
        migrations.AlterField(
            model_name='review',
            name='cool',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='funny',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='useful',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='useful',
            field=models.IntegerField(default=0),
        ),
    ]
