# Generated by Django 4.0.3 on 2022-04-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantManager', '0003_rename_publish_data_review_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='attributes',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
