# Generated by Django 4.0.3 on 2022-04-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantManager', '0007_auto_20220408_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=32),
        ),
    ]
