# Generated by Django 4.0.3 on 2022-04-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantManager', '0008_alter_restaurant_business_id_alter_review_review_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stars_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
